name: build and release

on:
  workflow_dispatch:
    inputs:      
      tag:
        description: 'Release Tag'
        required: true        

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update -y  
          sudo apt install libncurses5-dev python2 libtinfo5 -y      
          bash init_clang_12.sh
          
      - name: Set environment variable
        run: |
          echo "LPOS_KERNEL_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          
      - name: Building LPoS
        run: |
          export PATH=$HOME/:$PWD/toolchain/bin:$PATH
          bash build_kernel.sh -c

      - name: Building LPoS + KernelSU
        run: |
          export PATH=$HOME/:$PWD/toolchain/bin:$PATH
          bash build_kernel.sh -k          

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: "LPoS-${{ env.LPOS_KERNEL_VERSION }}-[S10 5G]"
          path: |
            out/LPoS*.xz
            out/KSU*.xz

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          name: "LPoS Kernel ${{ env.LPOS_KERNEL_VERSION }}"
          draft: false
          prerelease: false
          token: ${{ secrets.TOKEN }}          
          artifacts: "out/LPoS*.xz,out/KSU*.xz"
          body: "Commit SHA: ${{ github.sha }}"

      - name: Upload to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: "out/LPoS*.xz,out/KSU*.xz"
          format: html
          message_file: |
            <b>New Build found..! ðŸŽ‰</b>

            <b>Device :</b> S10 5G            
            
            <b>Repository:</b> ${{ github.repository }}
            
            <b>Commit SHA:</b> <a href="https://github.com/${{ github.repository }}/commit/${{github.sha}}">Click here</a>
            
            <b>Installation :</b> <a href="https://telegra.ph/LPoS-Kernel-Installation-Guide-02-09">Click here</a>
